### PR TITLE
**WIP** Fixing non-compiling macros

### LINKED ISSUE #594: Fix non-compiling macros
The following ROOT macros are currently not "compiling" (or ROOT fails loading them with .L). They should be fixed in order to reach a green state:

- [ ] /Detectors/EMCAL/testsimulation/drawEMCALgeometry.C 
- [ ] /Detectors/ITSMFT/ITS/macros/test/CheckClusterShape.C 
- [ ] /Detectors/ITSMFT/ITS/macros/test/CheckClusters.C 
- [ ] /Detectors/ITSMFT/ITS/macros/test/CheckDigits.C 
- [ ] /Detectors/ITSMFT/ITS/macros/test/CheckTracks.C 
- [ ] /Detectors/ITSMFT/ITS/macros/test/DisplayTrack.C 
- [ ] /Detectors/Passive/macro/PutFrameInTop.C 
- [ ] /Detectors/TOF/prototyping/drawTOFgeometry.C 
- [ ] /Detectors/TOF/prototyping/test.C 
- [ ] /Detectors/TPC/monitor/macro/RunCompareMode3.C 
- [ ] /Detectors/TPC/monitor/macro/RunFindAdcError.C 
- [ ] /Detectors/TPC/monitor/macro/RunSimpleEventDisplay.C 
- [ ] /Detectors/TPC/reconstruction/macro/RawClusterFinder.C 
- [ ] /Detectors/TPC/reconstruction/macro/convertClusters.C 
- [ ] /Detectors/TPC/reconstruction/macro/convertTracks.C 
- [ ] /Detectors/TPC/reconstruction/macro/dEdxRes.C 
- [ ] /Detectors/TPC/reconstruction/macro/runRawClusterFinder.C 
- [ ] /Detectors/TPC/reconstruction/macro/testClustererData.C 
- [ ] /Detectors/TPC/reconstruction/macro/testRawRead.C 
- [ ] /Detectors/TPC/reconstruction/macro/testTracks.C 
- [ ] /Detectors/TPC/simulation/macro/testHitsDigitsClusters.C 
- [ ] /Utilities/aliceHLTwrapper/macros/hltConfigurations.C 
- [ ] /Utilities/aliceHLTwrapper/macros/overlayClusters.C 
- [ ] /Utilities/aliceHLTwrapper/macros/runHLT.C 
- [ ] /macro/CheckClusters_mft.C 
- [ ] /macro/compare_cluster.C 
- [ ] /macro/putCondition.C 
- [ ] /macro/run_clus_its.C 
- [ ] /macro/run_clus_mft.C 
- [ ] /macro/run_digi.C 
- [ ] /macro/run_digi_its.C 
- [ ] /macro/run_digi_mft.C 
- [ ] /macro/run_reco_mft.C 
- [ ] /macro/run_sim_its.C 
- [ ] /macro/run_sim_its_ALP3.C 
- [ ] /macro/run_sim_mft.C 
- [ ]  /macro/run_trac_its.C

### PR DESCRIPTION
**Pull request by ZdravkoD**
Fixes #594

### CODE REVIEW

File: Detectors/TPC/reconstruction/macro/convertTracks.C [hunk 1]
```diff
@@ -8,19 +8,6 @@
 // granted to it by virtue of its status as an Intergovernmental Organization
 // or submit itself to any jurisdiction.
 
-#include <vector>
```
Comment (sawenzel) [inline Detectors/TPC/reconstruction/macro/convertTracks.C]: this is likely not the solution to go. Instead of taking away those headers, they should be protected by 
```
#if (!defined(__CINT__) && !defined(__CLING__)) || defined(__MAKECINT__)
#endif
```
